general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 11

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.98

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

[bell]
animation = "Linear"
duration = 20
command = { program = "paplay", args = ["/usr/share/sounds/freedesktop/stereo/bell.oga"] }

[cursor]
vi_mode_style = "None"
blink_interval = 750
blink_timeout = 0
unfocused_hollow = false
thickness = 0.15

[cursor.style]
shape = "Block"
blinking = "Always"

[colors.cursor]
text = "0x282828"
cursor = "0xcc241d"
