## GENERAL --------------------------------------------------------
general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

## ENVIRONMENT ----------------------------------------------------
[env]
TERM = "xterm-256color"

## FONTS configuration --------------------------------------------
[font]
normal = { family = "JetBrainsMono Nerd Font Mono" }
bold = { family = "JetBrainsMono Nerd Font Mono" }
italic = { family = "JetBrainsMono Nerd Font Mono" }
size = 12

## WINDOW ---------------------------------------------------------
[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.98

## BELL -----------------------------------------------------------
[bell]
animation = "Linear"
duration = 20
command = { program = "paplay", args = ["/usr/share/sounds/freedesktop/stereo/bell.oga"] }

## KEYBOARD -------------------------------------------------------
[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

## CURSOR ---------------------------------------------------------
[cursor]
vi_mode_style = "None"
blink_interval = 750
blink_timeout = 5
unfocused_hollow = false
thickness = 0.15

[cursor.style]
shape = "Block"
blinking = "On"

[colors.cursor]
text = "0x282828"
cursor = "0xcc241d"
